repository:
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: true

# Labels: define labels for Issues and Pull Requests
labels:
  - name: bug
    color: c10000
  - name: :nerd_face: 4geeks student
    color: 7057ff
  - name: enhancement
    color: a2eeef
  - name: first-timers-only
    color: 69db89
  - name: good first issue
    color: 7057ff
  - name: help wanted
    color: 008672
  - name: :star: P1
    color: fbca04
  - name: :star: P2
    color: fbca04
